import type { Metadata } from "next";
import inventory from "../data/inventory.json";

export const metadata: Metadata = { title: "Foster’s Car Alert — August 10, 2026", description: "Seven verified dealer cars at $5,000 or less near Leverett, Massachusetts." };
const cars = inventory.active;
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("en-US");
const checked = ["Arrow Auto Sales", "Affordable Used Cars", "Reliance Auto", "Auto Sales Center Inc", "Matt’s Auto Mall", "Depot Auto Sales", "Shelby Motor Cars", "Cottage Street Used Car Sales", "Ken’s Auto Sales", "AJ’s Auto Land", "Green River Auto", "Thrifty Springfield & Westfield", "Athol Motors", "CT Car Co", "Enfield Street Auto Sales", "Adam Auto Sales", "Gale Toyota", "Granite Auto Sales", "Driveline Motors", "Absolute Motors", "Stop & Drive Auto Sales"];

export default function Home() {
  const median = [...cars].sort((a,b)=>a.price-b.price)[Math.floor(cars.length/2)].price;
  return <main>
    <header className="hero"><nav><span className="wordmark">FOSTER’S</span><span className="date">MONDAY · AUG 10, 2026</span></nav><div className="hero-copy"><p className="eyebrow">DAILY CAR ALERT · LEVERETT, MASSACHUSETTS</p><h1>Seven cars worth<br/><em>a careful look.</em></h1><p className="dek">Dealer listings at $5,000 or less, within about an hour of home. Reliability and safety lead the ranking for a 16-year-old driver; price and mileage come second.</p></div><div className="stats"><div><strong>{cars.length}</strong><span>active cars</span></div><div><strong>{money.format(median)}</strong><span>median price</span></div><div><strong>60 min</strong><span>search radius</span></div></div></header>
    <section className="method"><span>How they’re ranked</span><p>This is a judgment call, not a formula. Model-specific reliability and verified crash protection are co-equal and dominate the order; mileage, repair exposure, price and dealer reputation break closer calls. Every car still needs service records, a VIN recall check and an independent inspection.</p></section>
    <section className="list" aria-label="Ranked car listings">{cars.map(car=><article className={`car-card ${car.rank===1?"winner":""}`} key={car.vin}><div className="photo-wrap">{car.image?<img src={car.image} alt={`Dealer photo of ${car.year} ${car.make} ${car.model}`}/>:<div className="photo-missing"><span>Photo unavailable</span><small>The source blocked retrieval.</small></div>}<span className="rank">#{car.rank}</span><span className="tag">{car.tag}</span></div><div className="car-copy"><div className="title-row"><div><p className="make">{car.year} · {car.make}</p><h2>{car.model}</h2><p className="trim">{car.trim}</p></div><div className="price"><strong>{money.format(car.price)}</strong><span>{number.format(car.miles)} miles</span></div></div><div className="dealer"><span>{car.dealer} · {car.town}</span><span>{car.rating}</span></div><div className="assessments"><div><span>Reliability</span><strong className={`level ${car.reliabilityLevel.toLowerCase().replace(" ","-")}`}>{car.reliabilityLevel}</strong><p>{car.reliability}</p></div><div><span>Safety</span><strong className={`level ${car.safetyLevel.toLowerCase().replace(" ","-")}`}>{car.safetyLevel}</strong><p>{car.safety}</p><a className="evidence" href={car.safetySource} target="_blank" rel="noreferrer">IIHS evidence ↗</a></div></div><div className="review"><h3>{car.verdict}</h3><p>{car.note}</p></div><div className="actions"><a href={car.url} target="_blank" rel="noreferrer">View original listing ↗</a><span>VIN {car.vin}</span></div></div></article>)}</section>
    <section className="coverage"><p className="eyebrow">SEARCH COVERAGE</p><h2>Checked broadly; only the best currently verified cars are shown.</h2><p className="coverage-note">Several sub-$5,000 listings were excluded because they carried substantially worse engine, transmission or crash-protection risk. Some individual listing pages blocked automated access; marketplace inventory pages still verified the VIN, dealer, price and photo shown here.</p><div className="dealer-grid">{checked.map(name=><span key={name}>{name}</span>)}</div></section>
    <section className="checklist"><div><p className="eyebrow">BEFORE MONEY CHANGES HANDS</p><h2>Three non-negotiables.</h2></div><ol><li><b>Independent inspection</b><span>Have a mechanic—not the seller—check structure, rust, leaks, brakes and tires.</span></li><li><b>VIN history + recalls</b><span>Confirm title, crashes and open safety recalls using the actual VIN.</span></li><li><b>Insurance quote</b><span>Price coverage for a 16-year-old before putting down a deposit.</span></li></ol></section>
    <footer><p>Fresh search completed August 10, 2026. All seven cars shown were re-verified on current dealer or marketplace inventory pages.</p><p>Individual listing pages were opened where sources allowed; ratings and equipment were not guessed. Availability can change—call first.</p></footer>
  </main>;
}
